### ISSUE TITLE
User Auth Ready for Review

### ISSUE THREAD

**Issue by guanw88** [guanw88/EventFul#2]
https://eventfullapp.herokuapp.com

**Comment by eshoule** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [ ] Can sign up a user
* Get a password too short error if my username is less than length of 6 but my password is longer
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [ ] The site should look exactly like the actual site
 * It looks like eventbrite has a much smaller input and button width
 * You need to make an style your splash page- '/' (this is part of user auth)
 * Style your errors to look like eventbrites
 * Some of your sizing/fonts/boldness look a little off
- [x] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)

Good job, George. Address the above comments and unchecked items, and then I can close this issue.

**Comment by guanw88** [comment]
Some home page elements require other elements (e.g. ability to show events) before I can fully style it, so I will be continuing working on the home page in the next phase.

Other issues should be resolved now.

https://eventfullapp.herokuapp.com
